FROM docker.io/ubuntu:16.04
MAINTAINER chi wang 

RUN apt-get update
RUN apt-get -y install build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev python-dev libmysqlclient-dev python-setuptools 
RUN apt-get install -y net-tools less

EXPOSE 18188
EXPOSE 18189

EXPOSE 19198
EXPOSE 19199
